commit

diff --git a/createpngset b/createpngset
--- a/createpngset
+++ b/createpngset
@@ -1,5 +1,10 @@
 #!/bin/bash
 basedir="$(dirname "$(readlink -f "${0}")")"
+#somechecks
+command -v inkscape >/dev/null 2>&1 || { echo >&2 "I require Inkscape but it's not installed.  Aborting."; exit 1; }
+command -v convert >/dev/null 2>&1 || { echo >&2 "I require ImageMagick but it's not installed.  Aborting."; exit 1; }
+command -v gtk-update-icon-cache-3.0 >/dev/null 2>&1 || { echo >&2 "I require libgtk-3-bin but it's not installed.  Aborting."; exit 1; }
+
 cd $basedir
 mkdir -p ivy/16
 mkdir -p ivy/22
@@ -62,5 +67,5 @@ cp -R /tmp/ivy-dev-tmp/* $basedir/ivy/48
 rm -R /tmp/ivy-dev-tmp
 cd $basedir
 gtk-update-icon-cache-3.0 ivy
-7z a -mx=9 -m0=PPMd -mmem=512m -ms=on ivy ivy
-echo "done"
+#7z a -mx=9 -m0=PPMd -mmem=512m -ms=on ivy ivy
+echo "done, you can now copy the ivy folder to your icon dir($HOME/.icons)"
